export const OP_CODES_ENUM = {
  'TL-DRY': 'TRUCKLOAD (DRY)',
  'TL-REEFER': 'TRUCKLOAD (REEFER)',
  'TL-FB': 'TRUCKLOAD (FLATBED)',
  'IMDL-R2R-D': 'INTERMODAL RAMP TO RAMP (DRY)',
  'IMDL-R2R-R': 'INTERMODAL RAMP TO RAMP (REEFER)',
  'IMDL-D2D-D': 'INTERMODAL DOOR TO DOOR (DRY)',
  'IMDL-D2D-R': 'INTERMODAL DOOR TO DOOR (REEFER)',
  LTL: 'LESS THAN TRUCKLAOD',
  'LTL-VOLUME': 'LTL (VOLUME LTR)',
  DRAY: 'DRAYAGE',
  AIR: 'AIR',
  OCEAN: 'OCEAN',
}
